name: Weekly SMS Job

on:
  schedule:
    - cron: '0 18 * * 5'  # Every Friday at 18:00 UTC (10:00 AM PST)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to version 3

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to version 4
      with:
        python-version: '3.x'  # Replace '3.x' with your specific version if needed

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install gspread oauth2client telnyx pandas
        pip install google-api-python-client  # Add this line if not already present

    - name: Create credentials.json from secret
      run: |
        printf '%s' "$GMAILAPISECRET" > credentials.json
      env:
        GMAILAPISECRET: ${{ secrets.GMAILAPISECRET }}

    - name: Run script
      run: |
        python send_sms.py
